In [1]:
print("hello world!")

hello world!


In [11]:
import numpy as np
rnd = np.random.default_rng()
arr = rnd.integers(low=14,high=67,size=(4,5))
arr


array([[16, 30, 21, 19, 20],
       [58, 21, 62, 55, 23],
       [50, 34, 43, 66, 57],
       [30, 29, 31, 58, 61]])

In [10]:
arr1=arr[:2,:]
print()
print("arr1:")
print(arr1)
arr2=arr[2:4,:]
print()
print("arr2:")
print(arr2)
el1 = arr1 == 18
el2 = arr2 > 28
print()
print(el1)
print()
print(el2)
print()
print(arr1[el1])
print(arr2[el2])
print("count 1:",arr1[el1].size)
print("count 2:",arr2[el2].size)




arr1:
[[35 47 34 46 57]
 [56 41 22 34 26]]

arr2:
[[48 26 22 63 65]
 [39 35 48 32 19]]

[[False False False False False]
 [False False False False False]]

[[ True False False  True  True]
 [ True  True  True  True False]]

[]
[48 63 65 39 35 48 32]
count 1: 0
count 2: 7


In [5]:
import pandas as pd
bcs = pd.Series([1,20,300,4000,500000,6000000,70000000,800000000],index=["one","two","three","four","five","six","seven","eight"])
print(bcs)
#############################
print()
print(bcs["six"]*100+bcs["seven"])
##################################
warframe = pd.DataFrame({
    "meme":["67","freddy fazbear","KeK"],
    "views":[67,18982,99999999999]
})
print()
print(warframe)
print()
print (warframe.columns)
warframe = warframe.drop(0)
print()
print(warframe)
warframe = warframe.drop(columns=["meme"])
print()
print(warframe)
print()
rows, cols = warframe.shape

print(f"Строк: {rows}")    
print(f"Столбцов: {cols}") 

count = (warframe == 18982).sum().sum()
print(f"Всего совпадений: {count}")



one              1
two             20
three          300
four          4000
five        500000
six        6000000
seven     70000000
eight    800000000
dtype: int64

670000000

             meme        views
0              67           67
1  freddy fazbear        18982
2             KeK  99999999999

Index(['meme', 'views'], dtype='str')

             meme        views
1  freddy fazbear        18982
2             KeK  99999999999

         views
1        18982
2  99999999999

Строк: 2
Столбцов: 1
Всего совпадений: 1
